### ISSUE TITLE
ClassCastException and immediate disconnect during "StreamAll" on log node

### ISSUE THREAD

**Issue by nanosek** [iot-dsa-v2/sdk-dslink-java-v2#102]
java.lang.ClassCastException: com.acuity.iot.dsa.dslink.sys.logging.SysLogService cannot be cast to org.iot.dsa.node.action.DSAction
	at org.iot.dsa.node.DSInfo.getAction(DSInfo.java:141)
	at com.acuity.iot.dsa.dslink.sys.logging.StreamableLogNode$3.getAction(StreamableLogNode.java:69)
	at com.acuity.iot.dsa.dslink.protocol.responder.DSInboundInvoke.writeColumns(DSInboundInvoke.java:362)
	at com.acuity.iot.dsa.dslink.protocol.responder.DSInboundInvoke.write(DSInboundInvoke.java:218)
	at com.acuity.iot.dsa.dslink.protocol.v1.DS1Session.writeResponse(DS1Session.java:410)
	at com.acuity.iot.dsa.dslink.protocol.v1.DS1Session.send(DS1Session.java:363)
	at com.acuity.iot.dsa.dslink.protocol.v1.DS1Session.doSendMessage(DS1Session.java:120)
	at com.acuity.iot.dsa.dslink.protocol.DSSession$WriteThread.run(DSSession.java:457)

[2019-02-11 08:37:18:810] INFO   [DSLink.sys.Connection] iothub2-local-localhost:8080 connected

**Comment by nanosek** [comment]
this is 0.51.0

**Comment by a-hansen** [comment]
Sorry, I don't know why, but I didn't get a notification of this.  Will take a look...

**Comment by a-hansen** [comment]
Fixed in 0.59.0
